/* Plugin generated by AMXX-Studio */

#include < amxmodx >
#include < amxmisc >
#include < zombieplague >

#define PLUGIN 		"[Avatar] Kill Efekt"
#define VERSION 	"0.3"
#define AUTHOR 		"adamCSzombie"

public plugin_init( ) 
{
	register_dictionary("zombie_plague.txt" );
	register_plugin( PLUGIN, VERSION, AUTHOR );
}

public zp_user_infected_post( id )
{
	if( !zp_get_user_nemesis( id ) )
	{
		set_hudmessage(125, 31, 122, -1.0, 0.22, 1, 0.0, 2.0, 1.0, 1.0, -1 );
		show_hudmessage(id ,"%L", LANG_PLAYER, "YOU_AVATAR" );
		ScreenFade( id, 2.0, 125, 31, 122, 200 );
	}
}

stock ScreenFade( plr, Float:fDuration, red, green, blue, alpha )
{
    new i = plr ? plr : get_maxplayers( );
    if( !i )
    {
        return 0;
    }
    
    message_begin( plr ? MSG_ONE : MSG_ALL, get_user_msgid( "ScreenFade" ), { 0, 0, 0 }, plr );
    write_short( floatround( 4096.0 * fDuration, floatround_round ) );
    write_short( floatround( 4096.0 * fDuration, floatround_round ) );
    write_short( 4096 );
    write_byte( red );
    write_byte( green );
    write_byte( blue );
    write_byte( alpha );
    message_end( );
    
    return 1;
}
